version: "2"

services:
  uwsgi:
    build: .
    command: >
      sh -cex "
        cd /last_fm;
        /virtualenv/bin/alembic upgrade head;
        exec /virtualenv/bin/uwsgi --master --module last_fm:app --processes 5 --enable-threads --chmod-socket=666 --socket /var/run/last_fm/uwsgi.socket;
      "
    env_file: .env
    links:
      - postgres
      - rabbitmq
      - redis
      - sync_scrobbles_daemon
    external_links:
      - twitteroverkill_api_1:twitter-overkill
    networks:
      - default
      - twitteroverkill_default
    restart: always
    volumes:
      - ./last_fm/static/artists:/last_fm/static/artists
      - ./last_fm/static/covers:/last_fm/static/covers
      - /var/run/last_fm

  gunicorn:
    build: .
    command: /virtualenv/bin/gunicorn --bind unix:/var/run/last_fm/gunicorn.socket --worker-class "geventwebsocket.gunicorn.workers.GeventWebSocketWorker" last_fm:api.app
    env_file: .env
    links:
      - postgres
      - rabbitmq
      - redis
    restart: always
    volumes_from:
      - uwsgi

  worker:
    build: .
    command: /virtualenv/bin/celery worker -A last_fm:celery -l INFO
    env_file: .env
    environment:
      C_FORCE_ROOT: "yes"
    links:
      - postgres
      - rabbitmq
      - redis
      - sync_scrobbles_daemon
    external_links:
      - twitteroverkill_api_1:twitter-overkill
    networks:
      - default
      - twitteroverkill_default
    restart: always
    volumes_from:
      - uwsgi

  scheduler:
    build: .
    command: /virtualenv/bin/celery beat -A last_fm:celery -s /var/lib/scheduler/schedule --pidfile=
    env_file: .env
    links:
      - rabbitmq
    restart: always
    volumes:
      - scheduler-data:/var/lib/scheduler
    volumes_from:
      - uwsgi

  sync_scrobbles_daemon:
    build: .
    command: /virtualenv/bin/python -m last_fm.sync_scrobbles_daemon
    env_file: .env
    links:
      - postgres
      - redis
    restart: always

  nginx:
    build: nginx
    ports:
      - "$PORT:80"
    restart: always
    volumes_from:
      - uwsgi

  postgres:
    image: postgres:latest
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: last_fm
      POSTGRES_USER: last_fm
      POSTGRES_PASSWORD: last_fm
    volumes:
      - "$POSTGRES_DATA_PATH:/var/lib/postgresql/data"

  rabbitmq:
    image: rabbitmq:latest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    image: redis:latest

networks:
  twitteroverkill_default:
    external: true

volumes:
  scheduler-data:
  rabbitmq-data:
