# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals

revision = '3de2f97d7967'
down_revision = None

from alembic import op
import sqlalchemy as sa

from last_fm.db import db
from last_fm.models import *


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'private_release_feed_user',
    sa.Column(u'feed_id', sa.Integer(), nullable=True),
    sa.Column(u'user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], [u'release_feed.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.add_column(u'release_feed', sa.Column('private', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'release_feed', 'private')
    op.drop_table(u'private_release_feed_user')
    ### end Alembic commands ###
