# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals

revision = '4ac3ec8c8fe3'
down_revision = u'3eb79129ab72'

from alembic import op
import sqlalchemy as sa

from last_fm.db import db
from last_fm.models import *


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('twitter_track_chart_milestones', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'twitter_track_chart_milestones')
    ### end Alembic commands ###
