# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals

revision = '4ba336c4c2bd'
down_revision = u'46bd812e1e9a'

from alembic import op
import sqlalchemy as sa

from last_fm.db import db
from last_fm.models import *
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'user_artist', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.drop_column(u'user_artist', u'artist')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user_artist', sa.Column(u'artist', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column(u'user_artist', 'artist_id')
    op.drop_table('artist')
    ### end Alembic commands ###
