# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals

revision = '4672e36fa037'
down_revision = u'4ba336c4c2bd'

from alembic import op
import sqlalchemy as sa

from last_fm.db import db
from last_fm.models import *


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anniversary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('anniversary', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], [u'artist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'user', sa.Column('twitter_track_artist_anniversaries', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('twitter_track_artist_anniversaries_min_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'twitter_track_artist_anniversaries_min_count')
    op.drop_column(u'user', 'twitter_track_artist_anniversaries')
    op.drop_table('anniversary')
    ### end Alembic commands ###
