# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals

revision = '46bd812e1e9a'
down_revision = u'3de2f97d7967'

from alembic import op
import sqlalchemy as sa

from last_fm.db import db
from last_fm.models import *
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'milestone_calculation_timestamp')
    op.add_column('user_artist', sa.Column('first_real_scrobble', sa.Integer(), nullable=True))
    op.add_column('user_artist', sa.Column('first_scrobble', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_artist', 'first_scrobble')
    op.drop_column('user_artist', 'first_real_scrobble')
    op.create_table(u'milestone_calculation_timestamp',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'uts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
