# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals

revision = '4182c82e6573'
down_revision = u'21b329f7322c'

from alembic import op
import sqlalchemy as sa

from last_fm.db import db
from last_fm.models import *


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('get',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('artist_image', sa.String(length=255), nullable=True),
    sa.Column('track', sa.String(length=255), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('get', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('get')
    ### end Alembic commands ###
