# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals

revision = '1d002a92f199'
down_revision = u'2688aee6c99'

from alembic import op
import sqlalchemy as sa

from last_fm.db import db
from last_fm.models import *


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('artist_expires_years', sa.Integer(), nullable=True))
    op.execute("UPDATE user SET artist_expires_years = 5")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'artist_expires_years')
    ### end Alembic commands ###
