# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals

revision = '4b625e2ed760'
down_revision = u'4bf1ffb34e26'

from alembic import op
import sqlalchemy as sa

from last_fm.db import db
from last_fm.models import *


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approximate_track_length', sa.Column('last_update', sa.DateTime(), nullable=True))
    op.execute("""
        UPDATE approximate_track_length SET last_update = (
            SELECT FROM_UNIXTIME(MAX(uts))
            FROM scrobble
            WHERE scrobble.artist = approximate_track_length.artist AND
                  scrobble.track = approximate_track_length.track
        )
    """)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approximate_track_length', 'last_update')
    ### end Alembic commands ###
