# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals

revision = '4bf1ffb34e26'
down_revision = u'4182c82e6573'

from alembic import op
import sqlalchemy as sa

from last_fm.db import db
from last_fm.models import *


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('twitter_track_gets', sa.Boolean(), nullable=True))
    op.execute("UPDATE user SET twitter_track_gets = twitter_track_artist_milestones")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'twitter_track_gets')
    ### end Alembic commands ###
