# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals

revision = '2c3975801252'
down_revision = u'1b2fb144acd7'

from alembic import op
import sqlalchemy as sa

from last_fm.db import db
from last_fm.models import *


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_similarity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_1_id', sa.Integer(), nullable=True),
    sa.Column('artist_2_id', sa.Integer(), nullable=True),
    sa.Column('match', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['artist_1_id'], [u'artist.id'], ),
    sa.ForeignKeyConstraint(['artist_2_id'], [u'artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_similarity')
    ### end Alembic commands ###
