# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals

revision = '21b329f7322c'
down_revision = u'1d002a92f199'

from alembic import op
import sqlalchemy as sa

from themyutils.sqlalchemy.types import MySqlPickleType

from last_fm.db import db
from last_fm.models import *


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('value', MySqlPickleType(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_data')
    ### end Alembic commands ###
