# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, unicode_literals

revision = '2fca63c0ee5b'
down_revision = u'1b005b1bd8fd'

from alembic import op
import sqlalchemy as sa

from last_fm.db import db
from last_fm.models import *
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'artist_expires_years')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('artist_expires_years', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
